/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as LoginRouteImport } from './routes/login'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as IndexRouteImport } from './routes/index'
import { Route as DashboardIndexRouteImport } from './routes/dashboard.index'
import { Route as DashboardStorageRouteImport } from './routes/dashboard.storage'
import { Route as DashboardSettingsRouteImport } from './routes/dashboard.settings'
import { Route as DashboardPaymentsRouteImport } from './routes/dashboard.payments'
import { Route as DashboardCollectionsRouteImport } from './routes/dashboard.collections'
import { Route as DashboardArchivesRouteImport } from './routes/dashboard.archives'
import { Route as DashboardArchiveIdRouteImport } from './routes/dashboard.archive.$id'

const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardIndexRoute = DashboardIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardStorageRoute = DashboardStorageRouteImport.update({
  id: '/storage',
  path: '/storage',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardSettingsRoute = DashboardSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardPaymentsRoute = DashboardPaymentsRouteImport.update({
  id: '/payments',
  path: '/payments',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardCollectionsRoute = DashboardCollectionsRouteImport.update({
  id: '/collections',
  path: '/collections',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardArchivesRoute = DashboardArchivesRouteImport.update({
  id: '/archives',
  path: '/archives',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardArchiveIdRoute = DashboardArchiveIdRouteImport.update({
  id: '/archive/$id',
  path: '/archive/$id',
  getParentRoute: () => DashboardRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRouteWithChildren
  '/login': typeof LoginRoute
  '/dashboard/archives': typeof DashboardArchivesRoute
  '/dashboard/collections': typeof DashboardCollectionsRoute
  '/dashboard/payments': typeof DashboardPaymentsRoute
  '/dashboard/settings': typeof DashboardSettingsRoute
  '/dashboard/storage': typeof DashboardStorageRoute
  '/dashboard/': typeof DashboardIndexRoute
  '/dashboard/archive/$id': typeof DashboardArchiveIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/dashboard/archives': typeof DashboardArchivesRoute
  '/dashboard/collections': typeof DashboardCollectionsRoute
  '/dashboard/payments': typeof DashboardPaymentsRoute
  '/dashboard/settings': typeof DashboardSettingsRoute
  '/dashboard/storage': typeof DashboardStorageRoute
  '/dashboard': typeof DashboardIndexRoute
  '/dashboard/archive/$id': typeof DashboardArchiveIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRouteWithChildren
  '/login': typeof LoginRoute
  '/dashboard/archives': typeof DashboardArchivesRoute
  '/dashboard/collections': typeof DashboardCollectionsRoute
  '/dashboard/payments': typeof DashboardPaymentsRoute
  '/dashboard/settings': typeof DashboardSettingsRoute
  '/dashboard/storage': typeof DashboardStorageRoute
  '/dashboard/': typeof DashboardIndexRoute
  '/dashboard/archive/$id': typeof DashboardArchiveIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/dashboard'
    | '/login'
    | '/dashboard/archives'
    | '/dashboard/collections'
    | '/dashboard/payments'
    | '/dashboard/settings'
    | '/dashboard/storage'
    | '/dashboard/'
    | '/dashboard/archive/$id'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/dashboard/archives'
    | '/dashboard/collections'
    | '/dashboard/payments'
    | '/dashboard/settings'
    | '/dashboard/storage'
    | '/dashboard'
    | '/dashboard/archive/$id'
  id:
    | '__root__'
    | '/'
    | '/dashboard'
    | '/login'
    | '/dashboard/archives'
    | '/dashboard/collections'
    | '/dashboard/payments'
    | '/dashboard/settings'
    | '/dashboard/storage'
    | '/dashboard/'
    | '/dashboard/archive/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  DashboardRoute: typeof DashboardRouteWithChildren
  LoginRoute: typeof LoginRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/': {
      id: '/dashboard/'
      path: '/'
      fullPath: '/dashboard/'
      preLoaderRoute: typeof DashboardIndexRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/storage': {
      id: '/dashboard/storage'
      path: '/storage'
      fullPath: '/dashboard/storage'
      preLoaderRoute: typeof DashboardStorageRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/settings': {
      id: '/dashboard/settings'
      path: '/settings'
      fullPath: '/dashboard/settings'
      preLoaderRoute: typeof DashboardSettingsRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/payments': {
      id: '/dashboard/payments'
      path: '/payments'
      fullPath: '/dashboard/payments'
      preLoaderRoute: typeof DashboardPaymentsRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/collections': {
      id: '/dashboard/collections'
      path: '/collections'
      fullPath: '/dashboard/collections'
      preLoaderRoute: typeof DashboardCollectionsRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/archives': {
      id: '/dashboard/archives'
      path: '/archives'
      fullPath: '/dashboard/archives'
      preLoaderRoute: typeof DashboardArchivesRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/archive/$id': {
      id: '/dashboard/archive/$id'
      path: '/archive/$id'
      fullPath: '/dashboard/archive/$id'
      preLoaderRoute: typeof DashboardArchiveIdRouteImport
      parentRoute: typeof DashboardRoute
    }
  }
}

interface DashboardRouteChildren {
  DashboardArchivesRoute: typeof DashboardArchivesRoute
  DashboardCollectionsRoute: typeof DashboardCollectionsRoute
  DashboardPaymentsRoute: typeof DashboardPaymentsRoute
  DashboardSettingsRoute: typeof DashboardSettingsRoute
  DashboardStorageRoute: typeof DashboardStorageRoute
  DashboardIndexRoute: typeof DashboardIndexRoute
  DashboardArchiveIdRoute: typeof DashboardArchiveIdRoute
}

const DashboardRouteChildren: DashboardRouteChildren = {
  DashboardArchivesRoute: DashboardArchivesRoute,
  DashboardCollectionsRoute: DashboardCollectionsRoute,
  DashboardPaymentsRoute: DashboardPaymentsRoute,
  DashboardSettingsRoute: DashboardSettingsRoute,
  DashboardStorageRoute: DashboardStorageRoute,
  DashboardIndexRoute: DashboardIndexRoute,
  DashboardArchiveIdRoute: DashboardArchiveIdRoute,
}

const DashboardRouteWithChildren = DashboardRoute._addFileChildren(
  DashboardRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  DashboardRoute: DashboardRouteWithChildren,
  LoginRoute: LoginRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
